---
title: "Palmer Penguins"
format:
  dashboard:
    orientation: columns
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: false
library(tidyverse)
library(palmerpenguins)
library(gt)
library(plotly)
library(gtsummary)
library(labelled)

data <- palmerpenguins::penguins

data <- data |> 
  set_variable_labels(
    island = 'Island',
    species = 'Species',
    bill_length_mm = 'Bill Length (mm)',
    bill_depth_mm = 'Bill Depth (mm)',
    flipper_length_mm = 'Flipper Length (mm)',
    body_mass_g = 'Body Mass (g)',
    sex = 'Sex',
    year = 'Year')

```

# Analysis

## 

```{r}
data |>
  select(-year) |>
  tbl_summary(
    by = species,
    missing = 'no',
    type = list(all_continuous() ~ 'continuous2')
  ) |>
  bold_labels() |>
  add_p()

```


## 

```{r}
plot_ly(
  data,
  x = ~ bill_length_mm,
  y = ~ bill_depth_mm,
  z = ~ flipper_length_mm,
  color = ~ species,
  size = 2
)
```

```{r}
local({
  plot <-
    ggplot(data, aes(x = species, y = bill_length_mm, fill = species)) +
    geom_boxplot() +
    theme_light() + 
    scale_fill_manual(
      values = c(
        '#64c4a4',
        '#fb8c64',
        '#8da4c8'
      )
    )
  
  ggplotly(plot)
})
```


# Raw Data

```{r}

data |>
  gt() |>
  opt_interactive(
    use_compact_mode = TRUE,
    use_highlight = TRUE,
    use_sorting = TRUE,
    use_pagination = TRUE,
    use_search = TRUE,
    use_filters = TRUE,
    use_resizers = FALSE,
    use_page_size_select = TRUE,
    page_size_default = 50
  )

```


